/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=callback/wrangler.jsonc --env-file=/Users/masaru/thth-exchange/out/2026-09-20_2.12.0_検証/writer/leave/types-qqd4xice/empty.env --include-runtime=false callback/worker-configuration.d.ts` (hash: 8d98a1ef9405c36255f76c977f986acb)
interface __BaseEnv_Env {
	DELETION_PUBLIC_LIMIT: RateLimit;
	AUTH_RATE_LIMIT: RateLimit;
	APPROVAL_PUBLIC_LIMIT: RateLimit;
	APPROVAL_VERIFY_LIMIT: RateLimit;
	APPROVAL_JOB_LIMIT: RateLimit;
	ASSETS: Fetcher;
	AUTH_RELAY: DurableObjectNamespace<import("./src/worker").AuthRelay>;
	APPROVAL_PERSON: DurableObjectNamespace<import("./src/worker").ApprovalPerson>;
	APPROVAL_SESSION: DurableObjectNamespace<import("./src/worker").ApprovalSession>;
	APPROVAL_ACCOUNT: DurableObjectNamespace<import("./src/worker").ApprovalAccount>;
	DELETION_INBOX: DurableObjectNamespace<import("./src/worker").DeletionInbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "AuthRelay" | "ApprovalPerson" | "ApprovalSession" | "ApprovalAccount" | "DeletionInbox";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
