/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=empty.env --include-runtime=false` (hash: c1bfcc01fbc5288e1d67c78b8bb7ef37)
interface __BaseEnv_Env {
	MEDIA_BUCKET: R2Bucket;
	MEDIA_PUBLIC_LIMIT: RateLimit;
	MEDIA_CONTROL_LIMIT: RateLimit;
	MEDIA_UPLOAD_LIMIT: RateLimit;
	DELETION_PUBLIC_LIMIT: RateLimit;
	AUTH_RATE_LIMIT: RateLimit;
	APPROVAL_PUBLIC_LIMIT: RateLimit;
	APPROVAL_VERIFY_LIMIT: RateLimit;
	APPROVAL_JOB_LIMIT: RateLimit;
	ASSETS: Fetcher;
	MEDIA_OBJECT: DurableObjectNamespace<import("./src/worker").MediaObject>;
	AUTH_RELAY: DurableObjectNamespace<import("./src/worker").AuthRelay>;
	APPROVAL_PERSON: DurableObjectNamespace<import("./src/worker").ApprovalPerson>;
	APPROVAL_SESSION: DurableObjectNamespace<import("./src/worker").ApprovalSession>;
	APPROVAL_ACCOUNT: DurableObjectNamespace<import("./src/worker").ApprovalAccount>;
	DELETION_INBOX: DurableObjectNamespace<import("./src/worker").DeletionInbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "AuthRelay" | "ApprovalPerson" | "ApprovalSession" | "ApprovalAccount" | "DeletionInbox" | "MediaObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
