/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=empty.env --include-runtime=false` (hash: 1d5e2e0d82eb3d766e90378b9723a63d)
interface __BaseEnv_Env {
	MEDIA_BUCKET: R2Bucket;
	DELETION_PUBLIC_LIMIT: RateLimit;
	AUTH_RATE_LIMIT: RateLimit;
	APPROVAL_PUBLIC_LIMIT: RateLimit;
	APPROVAL_VERIFY_LIMIT: RateLimit;
	APPROVAL_JOB_LIMIT: RateLimit;
	ASSETS: Fetcher;
	MEDIA_OBJECT: DurableObjectNamespace<import("./src/worker").MediaObject>;
	AUTH_RELAY: DurableObjectNamespace<import("./src/worker").AuthRelay>;
	APPROVAL_PERSON: DurableObjectNamespace<import("./src/worker").ApprovalPerson>;
	APPROVAL_SESSION: DurableObjectNamespace<import("./src/worker").ApprovalSession>;
	APPROVAL_ACCOUNT: DurableObjectNamespace<import("./src/worker").ApprovalAccount>;
	DELETION_INBOX: DurableObjectNamespace<import("./src/worker").DeletionInbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "AuthRelay" | "ApprovalPerson" | "ApprovalSession" | "ApprovalAccount" | "DeletionInbox" | "MediaObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
