"""Mastodon media wire/failure oracles, local generated bytes only."""
import contextlib
import copy
import email.parser
import email.policy
import hashlib
import http.server
import json
import os
from pathlib import Path
import secrets
import struct
import threading
import urllib.parse
from fractions import Fraction
import pytest
from thth import accounts, approval, core, handoff_cursor, inflight, media, media_delivery, mediaformats
from thth.adapters import base, mastodon, mastodon_media as mm
from tests.test_v213_media_foundation import png
from tests.test_v213_media_formats import box, mp4


def limits():
    return {'version':'4.5.0','configuration':{'statuses':{'max_media_attachments':5},'media_attachments':{'supported_mime_types':['image/png','video/mp4'],'image_size_limit':100000,'image_matrix_limit':1000,'video_size_limit':1000000,'video_matrix_limit':1000000,'video_frame_rate_limit':30,'description_limit':1500}}}


@pytest.fixture
def wire(monkeypatch):
    state={'caps':limits(),'upload':[(200,{'id':'1','type':'image','url':'https://example.invalid/1'})], 'poll':[], 'status':(200,{'id':'100','url':'https://example.invalid/100'}),'calls':[],'on_poll':None,'redirect':{},'on_upload':None}
    class Handler(http.server.BaseHTTPRequestHandler):
        def log_message(self,*a):pass
        def reply(self,code,body):
            data=body if isinstance(body,bytes) else json.dumps(body).encode();self.send_response(code);self.send_header('Content-Type','application/json');self.send_header('Content-Length',str(len(data)));self.end_headers();
            try:self.wfile.write(data)
            except (BrokenPipeError,ConnectionResetError):pass
        def do_GET(self):
            state['calls'].append(('GET',self.path,None,dict(self.headers)))
            if self.path=='/api/v2/instance':return self.reply(200,state['caps'])
            if state['on_poll']:state['on_poll']()
            self.reply(*state['poll'].pop(0))
        def do_POST(self):
            raw=self.rfile.read(int(self.headers['Content-Length']));state['calls'].append(('POST',self.path,raw,dict(self.headers)))
            if self.path in state['redirect']:
                self.send_response(state['redirect'][self.path]);self.send_header('Location','/must-not-follow');self.end_headers();return
            if self.path=='/api/v2/media':
                if state['on_upload']:state['on_upload']()
                self.reply(*state['upload'].pop(0))
            else:self.reply(*(state['status'].pop(0) if isinstance(state['status'],list) else state['status']))
    server=http.server.ThreadingHTTPServer(('127.0.0.1',0),Handler);thread=threading.Thread(target=server.serve_forever,daemon=True);thread.start()
    state['url']='http://127.0.0.1:'+str(server.server_port);monkeypatch.setattr(mm,'POLL_INTERVAL',0)
    try:yield state
    finally:server.shutdown();server.server_close();thread.join(3)


@pytest.fixture
def env(tmp_path,monkeypatch,wire):
    root=tmp_path.resolve()/'root';root.mkdir(mode=0o700);repo=root/'repo';repo.mkdir();(repo/'a.png').write_bytes(png())
    monkeypatch.setenv('THTH_ROOT',str(root));monkeypatch.delenv('THTH_ACCOUNTS_DIR',raising=False)
    cfg={'account':'alpha','media':'mastodon','instance':wire['url'],'repo_dir':str(repo),'production':True,'hashtags':False,'char_limit':500}
    monkeypatch.setattr(accounts,'load_account',lambda name:cfg)
    token=secrets.token_urlsafe(32);adapter=mastodon.MastodonAdapter(instance=wire['url'],access_token=token)
    monkeypatch.setattr(accounts,'load_token',lambda cfg:{'access_token':token})
    monkeypatch.setattr(core,'_append_run',lambda *a,**k:None)
    return cfg,adapter,repo


def invoke(env,fm=None,*,veto=None):
    cfg,adapter,repo=env;fm=fm or {'media':[{'file':'a.png','alt':'赤い点'}]}
    manifest=media.manifest_for(fm,cfg);state=accounts.state_dir_for('alpha')
    inflight.write(state,file='fixture',started='2030-01-01T00:00:00+09:00')
    result=media_delivery.publish(adapter,base.Post(text='body'),cfg=cfg,fm=fm,manifest=manifest,state_dir=state,before_publish=veto)
    return result,inflight.read(state),manifest


def posts(wire,path):return [x for x in wire['calls'] if x[:2]==('POST',path)]


def test_wire_same_public_bytes_alt_order_and_private_journal(env,wire):
    cfg,adapter,repo=env;(repo/'b.png').write_bytes(png())
    wire['upload']=[(200,{'id':str(i),'type':'image','url':'https://example.invalid/'+str(i)}) for i in (8,3)]
    fm={'media':[{'file':'a.png','alt':'一行・二行 🌿'},{'file':'b.png','alt':'別の説明'}],'post_options':{'sensitive':True,'spoiler_text':'予告','language':'ja','focus':[[0.2,-1],[1,0]]}}
    result,journal,manifest=invoke(env,fm);assert result.post_id=='100' and journal['media']['phase']=='published'
    assert stat_mode(accounts.state_dir_for('alpha')+'/inflight.json')==0o600
    for call,row in zip(posts(wire,'/api/v2/media'),manifest['files']):
        msg=email.parser.BytesParser(policy=email.policy.default).parsebytes(('Content-Type: '+call[3]['Content-Type']+'\r\n\r\n').encode()+call[2])
        fields={p.get_param('name',header='Content-Disposition'):p for p in msg.iter_parts()}
        assert fields['description'].get_payload(decode=True).decode()==row['alt']
        assert hashlib.sha256(fields['file'].get_payload(decode=True)).hexdigest()==row['public_sha256']
        assert fields['file'].get_content_type()=='image/png'
    form=urllib.parse.parse_qs(posts(wire,'/api/v1/statuses')[0][2].decode())
    assert form['media_ids[]']==['8','3'] and form['sensitive']==['true'] and form['spoiler_text']==['予告']
    cap=mm.cached(cfg);assert cap['instance']==wire['url'] and cap['observed_at'] and cap['version']=='4.5.0'


def stat_mode(path):return os.stat(path).st_mode&0o777


@pytest.mark.parametrize('poll',[(200,{'id':'1','type':'image','url':'https://example.invalid/1'}),(422,{'error':'processing failed'}),(404,{'error':'absent'}),(500,{'error':'bad'}),(200,{'id':'2','type':'image','url':'https://example.invalid/2'}),(200,{'id':'1','type':'image','url':None})])
def test_pending_206_then_terminal(env,wire,poll):
    wire['upload']=[(202,{'id':'1','type':'image','url':None})];wire['poll']=[(206,{}),poll]
    result,journal,_=invoke(env)
    expected=poll[0]==200 and poll[1].get('id')=='1' and poll[1].get('url')
    assert bool(result.post_id)==bool(expected) and len(posts(wire,'/api/v1/statuses'))==int(bool(expected))
    if not expected:assert result.error and journal['media']['phase']=='held'


@pytest.mark.parametrize('field,value,reason',[('max_media_attachments',0,'capability'),('max_media_attachments',True,'capability'),('description_limit',None,'capability'),('description_limit',2,'alt'),('image_size_limit',1,'bytes'),('image_matrix_limit',False,'capability'),('supported_mime_types',['image/jpeg'],'unsupported_attachment')])
def test_capabilities_fail_before_upload(env,wire,field,value,reason):
    target=wire['caps']['configuration']['statuses' if field=='max_media_attachments' else 'media_attachments'];target[field]=value
    result,journal,_=invoke(env);assert result.error and reason in result.error;assert not posts(wire,'/api/v2/media') and not posts(wire,'/api/v1/statuses')


def test_instance_exact_count_size_matrix_alt_bounds(env,wire):
    cfg,adapter,repo=env;fm={'media':[]}
    for i in range(5):(repo/f'{i}.png').write_bytes(png());fm['media'].append({'file':f'{i}.png','alt':'字'})
    wire['caps']['configuration']['media_attachments'].update(image_size_limit=len(png()),image_matrix_limit=1,description_limit=1)
    wire['upload']=[(200,{'id':str(i+1),'type':'image','url':'https://example.invalid/a'}) for i in range(5)]
    result,_,_=invoke(env,fm);assert result.post_id=='100' and len(posts(wire,'/api/v2/media'))==5
    (repo/'six.png').write_bytes(png());fm['media'].append({'file':'six.png','alt':'字'});wire['calls']=[]
    result,_,_=invoke(env,fm);assert 'count' in result.error and not posts(wire,'/api/v2/media')


def test_stale_during_processing_post_zero(env,wire):
    cfg,adapter,repo=env;wire['upload']=[(202,{'id':'1','type':'image','url':None})];wire['poll']=[(200,{'id':'1','type':'image','url':'https://example.invalid/1'})]
    wire['on_poll']=lambda:(repo/'a.png').write_bytes(png()+b'changed')
    result,journal,_=invoke(env);assert not result.post_id and 'source_changed' in result.error
    assert not posts(wire,'/api/v1/statuses') and journal['media']['phase'] in ('held','ready')


def test_explicit_final_veto_after_upload(env,wire):
    result,journal,_=invoke(env,veto=lambda:'approval_stale' if posts(wire,'/api/v2/media') else None)
    assert result.error=='approval_stale' and not posts(wire,'/api/v1/statuses')
    assert result.failure=='media_held'


@pytest.mark.parametrize('status,body',[(500,{}),(202,{}),(200,{'id':'1','type':'image','url':None})])
def test_upload_unknown_keeps_intent_no_status(env,wire,status,body):
    wire['upload']=[(status,body)];result,journal,_=invoke(env)
    assert result.failure=='media_ambiguous' and journal['media']['phase']=='unknown' and not posts(wire,'/api/v1/statuses')


def test_idempotency_binds_intent_and_text_only_legacy(env):
    cfg,adapter,repo=env;a=base.Post('body');old=hashlib.sha256(('mastodon\x1f'+adapter.instance+'\x1fpublic\x1f\x1fbody').encode()).hexdigest();assert adapter._idempotency_key(a,'public')==old
    manifest=media.manifest_for({'media':[{'file':'a.png','alt':'first'}]},cfg);a.media_manifest=manifest;key=adapter._idempotency_key(a,'public')
    for field,value in [('alt','second'),('public_sha256','f'*64)]:
        m=copy.deepcopy(manifest);m['files'][0][field]=value;a.media_manifest=m
        assert adapter._idempotency_key(a,'public')!=key
    a.media_manifest=manifest;assert adapter._idempotency_key(a,'public')==key


def video_timing(rows,*,scale=1000):
    ticks=sum(n*d for n,d in rows);count=sum(n for n,d in rows)
    timing=box(b'mdhd',b'\0'*12+struct.pack('>II',scale,ticks)+b'\0'*4)
    sample=b'\0'*24+struct.pack('>HH',640,480)+b'\0'*50
    table=box(b'stts',b'\0'*4+struct.pack('>I',len(rows))+b''.join(struct.pack('>II',n,d) for n,d in rows))+box(b'stsz',b'\0'*4+struct.pack('>II',1,count))+box(b'stsd',b'\0'*4+struct.pack('>I',1)+box(b'avc1',sample))
    raw=mp4();needle=box(b'mdia',box(b'hdlr',b'\0'*8+b'vide'+b'\0'*12));replacement=box(b'mdia',box(b'hdlr',b'\0'*8+b'vide'+b'\0'*12)+timing+box(b'minf',box(b'stbl',table)))
    # Rebuild known fixture ancestors, never transform production bytes.
    mvhd=b'\0'*12+struct.pack('>II',scale,ticks)+b'\0'*80;tkhd=b'\0'*76+struct.pack('>II',640<<16,480<<16)
    return box(b'ftyp',b'isom\0\0\0\0isom')+box(b'moov',box(b'mvhd',mvhd)+box(b'trak',box(b'tkhd',tkhd)+replacement))+box(b'mdat',b'synthetic')


@pytest.mark.parametrize('rows,rate',[([(30,1000)],Fraction(30,1)),([(10,500),(20,1250)],Fraction(30,1)),([(31,1000)],Fraction(30,1))])
def test_video_average_not_instantaneous_rate(env,rows,rate):
    # First/second 30fps, third uses a different total frame count, same fps.
    cfg,adapter,repo=env;p=repo/'v.mp4';p.write_bytes(video_timing(rows,scale=30000))
    fd=os.open(p,os.O_RDONLY)
    try:w,h,actual=mediaformats.video_metrics(fd,p.stat().st_size)
    finally:os.close(fd)
    assert (w,h)==(640,480) and actual==rate


def test_video_floor_rate_and_bytes_unchanged(env,wire):
    cfg,adapter,repo=env;p=repo/'v.mp4';raw=video_timing([(309,1000)],scale=30900);p.write_bytes(raw)
    wire['upload']=[(202,{'id':'1','type':'video','url':None})];wire['poll']=[(200,{'id':'1','type':'video','url':'https://example.invalid/v'})]
    result,_,_=invoke(env,{'media':[{'file':'v.mp4','alt':'動画'}]});assert result.post_id=='100' and p.read_bytes()==raw


def test_journal_fsync_failure_before_upload(env,wire,monkeypatch):
    def fail(*a):raise OSError('synthetic fsync')
    monkeypatch.setattr(media_delivery,'_save',fail)
    result,journal,_=invoke(env);assert result.error=='media_journal_unavailable' and not wire['calls']


def test_actual_send_confirm_and_restart_unknown_no_reupload(env,wire):
    cfg,adapter,repo=env;rows=[{'file':'a.png','alt':'点'}];factory=lambda *a:adapter
    first=core.send_once('alpha',text='',media_rows=rows,production_flag=False,adapter_factory=factory,log=lambda x:None)
    wire['status']=(500,{})
    result=core.send_once('alpha',text='',media_rows=rows,production_flag=True,confirm=first.digest,adapter_factory=factory,log=lambda x:None)
    assert result.action=='inflight' and len(posts(wire,'/api/v2/media'))==1
    second=core.send_once('alpha',text='',media_rows=rows,production_flag=True,confirm=first.digest,adapter_factory=factory,log=lambda x:None)
    assert second.action=='inflight' and len(posts(wire,'/api/v2/media'))==1


@pytest.mark.parametrize('phase', ['prepared','uploading','processing','ready','publishing','published'])
def test_journal_fault_no_next_side_effect_and_restart_block(env,wire,monkeypatch,phase):
    cfg,adapter,repo=env
    if phase=='processing':wire['upload']=[(202,{'id':'1','type':'image','url':None})]
    original=media_delivery._save;failed=[]
    def save(name,data):
        if data['media']['phase']==phase:
            failed.append(phase);raise OSError('synthetic persistence failure')
        return original(name,data)
    monkeypatch.setattr(media_delivery,'_save',save)
    result,journal,_=invoke(env)
    assert failed and result.error and not result.post_id
    assert len(posts(wire,'/api/v2/media'))==int(phase not in ('prepared','uploading'))
    assert len(posts(wire,'/api/v1/statuses'))==int(phase=='published')
    count=len(wire['calls'])
    again=core.send_once('alpha',text='body',production_flag=True,confirm='irrelevant',adapter_factory=lambda *a:adapter,log=lambda _:None,media_rows=[{'file':'a.png','alt':'赤い点'}])
    assert again.action=='inflight' and len(wire['calls'])==count


@pytest.mark.parametrize('link',['symlink','hardlink','fifo'])
def test_media_private_journal_rejects_special_leaf(env,wire,link):
    cfg,adapter,repo=env;directory=Path(accounts.state_dir_for('alpha'));directory.mkdir(parents=True,exist_ok=True)
    target=directory/'inflight.json';outside=repo/'foreign';outside.write_text('{}')
    if link=='symlink':target.symlink_to(outside)
    elif link=='hardlink':os.link(outside,target)
    else:os.mkfifo(target)
    before=outside.read_bytes()
    with pytest.raises((OSError,ValueError)):media_delivery._save('alpha',{'media':{}})
    assert outside.read_bytes()==before and not wire['calls']


@pytest.mark.parametrize('directory_failure',[False,True])
def test_actual_file_and_directory_fsync_failure_no_false_return(env,monkeypatch,directory_failure):
    import stat
    cfg,adapter,repo=env;directory=Path(accounts.state_dir_for('alpha'));directory.mkdir(parents=True,exist_ok=True)
    target=directory/'inflight.json';target.write_text('{"old":true}');before=target.read_bytes();real=os.fsync;calls=[]
    def fail(fd):
        isdir=stat.S_ISDIR(os.fstat(fd).st_mode)
        if isdir==directory_failure:calls.append(isdir);raise OSError('synthetic fsync EIO')
        real(fd)
    monkeypatch.setattr(media_delivery.os,'fsync',fail)
    with pytest.raises(OSError):media_delivery._save('alpha',{'new':True})
    assert calls and not list(directory.glob('.media-inflight-*'))
    assert (target.read_bytes()==before)==(not directory_failure)


def test_lint_fresh_limits_no_credentials_and_production_rechecks(env,wire):
    cfg,adapter,repo=env;fm={'media':[{'file':'a.png','alt':'赤い点'}]}
    assert 'capability_unobserved' in media_delivery.cached_note(cfg) and not wire['calls']
    cap=mm.capabilities(limits(),wire['url']);cap['image_size_limit']=1;mm.cache(cfg,cap)
    notes=media_delivery.lint_notes(cfg,fm)
    assert all(n.startswith('warning:') for n in notes)
    assert all('Authorization' not in call[3] for call in wire['calls'])
    assert not posts(wire,'/api/v2/media')
    wire['caps']['configuration']['media_attachments']['image_size_limit']=1
    assert media_delivery.lint_notes(cfg,fm)==['media_limit_exceeded: bytes']
    result,_,_=invoke(env);assert 'bytes' in result.error and not posts(wire,'/api/v2/media')
    other={**cfg,'instance':'https://different.invalid'};assert mm.cached(other) is None


@pytest.mark.parametrize('options',[{'quote_approval_policy':'public'},{'visibility':'private'}])
def test_unimplemented_post_options_refused_without_network(env,wire,options):
    result,_,_=invoke(env,{'media':[{'file':'a.png','alt':'点'}],'post_options':options})
    assert 'unsupported_attachment: mastodon/' in result.error and not wire['calls']


def test_average_rate_unknown_and_over_limit_do_not_upload(env,wire):
    cfg,adapter,repo=env;path=repo/'v.mp4';fm={'media':[{'file':'v.mp4','alt':'動画'}]}
    path.write_bytes(mp4());result,_,_=invoke(env,fm)
    assert 'unverifiable' in result.error and not posts(wire,'/api/v2/media')
    path.write_bytes(video_timing([(31,1000)],scale=31000));result,_,_=invoke(env,fm)
    assert 'frame_rate' in result.error and not posts(wire,'/api/v2/media')


def test_send_success_records_compact_media_receipt(env,wire):
    from thth import sent
    cfg,adapter,repo=env;rows=[{'file':'a.png','alt':'点'}]
    dry=core.send_once('alpha',text='',media_rows=rows,adapter_factory=lambda *a:adapter,log=lambda _:None)
    done=core.send_once('alpha',text='',media_rows=rows,production_flag=True,confirm=dry.digest,adapter_factory=lambda *a:adapter,log=lambda _:None)
    assert done.action=='post' and done.post_id=='100' and inflight.read(accounts.state_dir_for('alpha')) is None
    stored=sent.read(accounts.state_dir_for('alpha'),'100')
    assert stored['media']==[{'sha256':hashlib.sha256(png()).hexdigest(),'kind':'image','alt_present':True,'remote_id':'1'}]
    assert '点' not in json.dumps(stored['media'],ensure_ascii=False)


def test_two_stage_cli_send_actual_multipart(env,wire,monkeypatch,capsys):
    from thth import cli,read_coordination
    cfg,adapter,repo=env;monkeypatch.setattr(core,'_default_adapter_factory',lambda *a:adapter)
    monkeypatch.setattr(read_coordination,'invoke',lambda args,name,fn=None:fn() if fn else args.func(args))
    argv=['send','alpha','--media','a.png','--alt','点']
    assert cli.main(argv)==0;shown=capsys.readouterr().out
    digest=next(line.split(': ',1)[1] for line in shown.splitlines() if line.startswith('digest: '))
    assert not posts(wire,'/api/v2/media')
    assert cli.main(argv+['--production','--confirm',digest])==0
    assert len(posts(wire,'/api/v2/media'))==len(posts(wire,'/api/v1/statuses'))==1


def test_provider_cannot_silently_drop_prepared_files(env,wire):
    cfg,adapter,repo=env
    class Legacy:
        def publish(self,*a,**kw):pytest.fail('must not drop media')
    result,_,_=invoke((cfg,Legacy(),repo))
    assert result.error=='media_provider_unavailable' and not wire['calls']


@pytest.mark.parametrize('drift',['none','alt','body','order','revoke'])
def test_v1_git_approve_publish_and_final_drift_veto(tmp_path,isolated_account_factory,wire,monkeypatch,drift):
    from tests.conftest import init_git_pair,make_queue_text,run_git,approve_via_cli
    from thth import queuefile
    name='alpha';raw=make_queue_text({'account':name,'status':'draft','approved_sha':'','topic':''},body='## mastodon\n\n本文。\n',media='mastodon')
    raw=raw.replace('\n---\n','\nmedia:\n  - file: a.png\n    alt: 点A\n  - file: b.png\n    alt: 点B\n---\n',1)
    pair=init_git_pair(tmp_path,seed_content=raw);repo=Path(pair['work']);path=Path(pair['queue_dir'])/'a.md'
    (repo/'a.png').write_bytes(png());(repo/'b.png').write_bytes(png())
    run_git(str(repo),['add','.']);run_git(str(repo),['commit','-m','synthetic media']);run_git(str(repo),['push'])
    account=isolated_account_factory(name=name,repo_dir=str(repo),media='mastodon',instance=wire['url'],production=True,hashtags=False,char_limit=500,quiet_hours=None,min_interval_hours=0)
    approved=approve_via_cli(path);assert approved.returncode==0,approved.stderr
    token=secrets.token_urlsafe(32);monkeypatch.setattr(accounts,'load_token',lambda _: {'access_token':token})
    adapter=mastodon.MastodonAdapter(instance=wire['url'],access_token=token)
    wire['upload']=[(202,{'id':'1','type':'image','url':None}),(200,{'id':'2','type':'image','url':'https://example.invalid/2'})]
    wire['poll']=[(200,{'id':'1','type':'image','url':'https://example.invalid/1'})]
    def mutate():
        if drift!='none':
            before=path.read_text();after=before.replace('status: approved','status: draft') if drift=='revoke' else before.replace('点A','別のalt') if drift=='alt' else before.replace('本文。','変更本文。') if drift=='body' else before.replace('file: a.png','file: temporary.png').replace('file: b.png','file: a.png').replace('file: temporary.png','file: b.png')
            path.write_text(after)
    wire['on_poll']=mutate
    result=core.throw_once(name,production_flag=True,adapter_factory=lambda *a:adapter,log=lambda _:None,bypass_pace=True)
    if drift=='none':
        assert result.action=='post',result
        assert queuefile.parse(str(path)).get('status')=='posted'
    else:
        assert result.action=='inflight' and not posts(wire,'/api/v1/statuses')
        assert queuefile.parse(str(path)).get('status')==('draft' if drift=='revoke' else 'approved')


@pytest.mark.parametrize('late',['none','second_upload_error','revoke','deadline'])
def test_v2_media_per_segment_and_parent_survive_git_writeback(tmp_path,isolated_account_factory,wire,monkeypatch,late):
    import datetime
    from tests.conftest import init_git_pair,run_git,approve_via_cli
    from tests.test_thread_publish import bundle_text,REL
    from thth import threadthrow,threadrun,queuefile
    now=__import__('thth.jst',fromlist=['now_jst']).now_jst();at=now.isoformat();until=(now+datetime.timedelta(hours=1)).isoformat()
    raw=bundle_text(account='alpha',segments=['一段目','二段目'],status='draft',topic='',publish_at=at,continue_until=until).replace('## threads','## mastodon')
    raw=raw.replace('  - index: 1','  - index: 1\n    media:\n      - file: a.png\n        alt: 一').replace('  - index: 2','  - index: 2\n    media:\n      - file: b.png\n        alt: 二')
    pair=init_git_pair(tmp_path,seed_content=raw,seed_name='thread.md');repo=Path(pair['work'])
    (repo/'a.png').write_bytes(png());(repo/'b.png').write_bytes(png())
    run_git(str(repo),['add','.']);run_git(str(repo),['commit','-m','synthetic files']);run_git(str(repo),['push'])
    isolated_account_factory(name='alpha',repo_dir=str(repo),media='mastodon',instance=wire['url'],production=True,hashtags=False,char_limit=500,quiet_hours=None,min_interval_hours=0)
    approved=approve_via_cli(repo/REL);assert approved.returncode==0,approved.stderr
    token=secrets.token_urlsafe(32);monkeypatch.setattr(accounts,'load_token',lambda _: {'access_token':token})
    adapter=mastodon.MastodonAdapter(instance=wire['url'],access_token=token)
    wire['upload']=[(200,{'id':str(i),'type':'image','url':'https://example.invalid/'+str(i)}) for i in (1,2)]
    wire['status']=[(200,{'id':'100'}),(200,{'id':'101'})]
    if late=='second_upload_error':wire['upload'][1]=(500,{})
    if late in ('revoke','deadline'):
        wire['upload'][0]=(202,{'id':'1','type':'image','url':None})
        wire['poll']=[(200,{'id':'1','type':'image','url':'https://example.invalid/1'})]
        def stop():
            if late=='revoke':(repo/REL).write_text((repo/REL).read_text().replace('status: approved','status: draft'))
            else:monkeypatch.setattr(__import__('thth.jst',fromlist=['now_jst']),'now_jst',lambda:now+datetime.timedelta(hours=2))
        wire['on_poll']=stop
    results=threadthrow.publish_bundle('alpha',REL,adapter_factory=lambda *a:adapter,now=now,log=lambda _:None)
    if late!='none':
        assert not any(r.action=='published' for r in results[1:])
        assert len(posts(wire,'/api/v1/statuses'))==int(late=='second_upload_error')
        assert inflight.read(accounts.state_dir_for('alpha')) is not None
        previous=len(wire['calls']);again=threadthrow.publish_bundle('alpha',REL,adapter_factory=lambda *a:adapter,now=now,log=lambda _:None)
        assert len(wire['calls'])==previous and all(r.action!='published' for r in again)
        return
    assert [r.action for r in results]==['published','published'],results
    requests=posts(wire,'/api/v1/statuses');assert len(requests)==2
    assert urllib.parse.parse_qs(requests[1][2].decode())['in_reply_to_id']==['100']
    run=threadrun.load(results[0].run_id);assert [row['media'][0]['remote_id'] for row in run['posts']]==['1','2']


@pytest.mark.parametrize('code',[301,302,303,307,308])
def test_upload_redirect_not_followed(env,wire,code):
    wire['redirect']['/api/v2/media']=code
    result,journal,_=invoke(env)
    assert result.failure=='media_ambiguous' and journal['media']['phase']=='unknown'
    assert not any('/must-not-follow' in x[1] for x in wire['calls']) and not posts(wire,'/api/v1/statuses')


@pytest.mark.parametrize('code',[400,401,403,404,413,422,429])
def test_first_upload_definite_refusal_is_not_unknown(env,wire,code):
    marker=secrets.token_urlsafe(32);wire['upload']=[(code,{'error':marker})]
    result,journal,_=invoke(env)
    assert result.failure=='publish_definite' and journal['media']['phase']=='failed'
    assert marker not in json.dumps(journal) and marker not in str(result) and str(code) in result.error
    assert not posts(wire,'/api/v1/statuses')


def test_processing_deadline_preserves_known_id_and_does_not_post(env,wire,monkeypatch):
    wire['upload']=[(202,{'id':'1','type':'image','url':None})]
    original=mm.time.monotonic;counter=[0]
    def clock():counter[0]+=1;return 1000+counter[0]*200
    monkeypatch.setattr(mm.time,'monotonic',clock)
    result,journal,_=invoke(env)
    assert result.failure=='media_held' and result.error=='media_processing_timeout'
    assert journal['media']['remote_ids']==['1'] and not posts(wire,'/api/v1/statuses')


def test_real_snapshot_bytes_not_changed_source_after_upload(env,wire):
    cfg,adapter,repo=env;original=(repo/'a.png').read_bytes()
    wire['on_upload']=lambda:(repo/'a.png').write_bytes(b'X'*len(original))
    result,journal,manifest=invoke(env)
    payload=posts(wire,'/api/v2/media')[0]
    msg=email.parser.BytesParser(policy=email.policy.default).parsebytes(('Content-Type: '+payload[3]['Content-Type']+'\r\n\r\n').encode()+payload[2])
    sent=next(p.get_payload(decode=True) for p in msg.iter_parts() if p.get_filename())
    assert sent==original and hashlib.sha256(sent).hexdigest()==manifest['files'][0]['public_sha256']
    assert 'source_changed' in result.error and not posts(wire,'/api/v1/statuses')


@pytest.mark.parametrize('status,body',[(200,b'not JSON'),(200,{}),(201,{'id':42}),(500,{})])
def test_status_response_uncertain_preserves_all_media_ids(env,wire,status,body):
    wire['status']=(status,body)
    result,journal,_=invoke(env)
    assert result.failure=='media_ambiguous' and journal['media']['phase']=='unknown'
    assert journal['media']['remote_ids']==['1'] and len(posts(wire,'/api/v1/statuses'))==1


def test_silent_video_may_be_classified_gifv_by_provider(env,wire):
    cfg,adapter,repo=env;(repo/'v.mp4').write_bytes(video_timing([(30,1000)],scale=30000))
    wire['upload']=[(200,{'id':'1','type':'gifv','url':'https://example.invalid/v'})]
    result,_,_=invoke(env,{'media':[{'file':'v.mp4','alt':'動画'}]});assert result.post_id=='100'


def test_sent_record_failure_is_bounded_keeps_published_intent(env,wire,monkeypatch):
    from thth import sent
    cfg,adapter,repo=env;rows=[{'file':'a.png','alt':'点'}]
    first=core.send_once('alpha',text='',media_rows=rows,adapter_factory=lambda *a:adapter,log=lambda _:None)
    def fail(*a,**k):raise OSError('synthetic sent write failure')
    monkeypatch.setattr(sent,'write',fail)
    done=core.send_once('alpha',text='',media_rows=rows,production_flag=True,confirm=first.digest,adapter_factory=lambda *a:adapter,log=lambda _:None)
    assert done.action=='inflight' and done.post_id=='100' and done.error=='media_record_unconfirmed'
    journal=inflight.read(accounts.state_dir_for('alpha'));assert journal['media']['phase']=='published'
    before=len(wire['calls']);again=core.send_once('alpha',text='',media_rows=rows,production_flag=True,confirm=first.digest,adapter_factory=lambda *a:adapter,log=lambda _:None)
    assert again.action=='inflight' and len(wire['calls'])==before


def test_stop_during_processing_retains_intent_no_new_status_or_state(env,wire):
    from thth import leave_gate
    cfg,adapter,repo=env;leave_gate.bind(adapter,cfg)
    wire['upload']=[(202,{'id':'1','type':'image','url':None})];wire['poll']=[(200,{'id':'1','type':'image','url':'https://example.invalid/1'})]
    before=[]
    def stop():
        before.append(Path(accounts.state_dir_for('alpha'),'inflight.json').read_bytes())
        leaf=leave_gate.location()/'alpha.json';leaf.write_text('{}');leaf.chmod(0o600)
    wire['on_poll']=stop
    result,journal,_=invoke(env)
    assert result.error=='account_stopped' and result.failure=='media_held'
    assert not posts(wire,'/api/v1/statuses') and journal['media']['phase']=='processing'
    assert Path(accounts.state_dir_for('alpha'),'inflight.json').read_bytes()==before[0]


def test_public_lint_overlimit_and_missing_capabilities_are_errors(env,wire):
    from thth import lint
    cfg,adapter,repo=env;path=repo/'draft.md'
    path.write_text('---\nthth: 1\naccount: alpha\nstatus: draft\npublish_at: 2030-01-01T12:00:00+09:00\nmedia:\n  - file: a.png\n    alt: 点\n---\n## mastodon\n\n本文\n')
    wire['caps']['configuration']['media_attachments']['image_size_limit']=1
    errors=[e for e in lint.lint_file(str(path)) if not lint.is_warning(e)]
    assert 'media_limit_exceeded: bytes' in errors
    del wire['caps']['configuration']['media_attachments']['image_size_limit']
    errors=[e for e in lint.lint_file(str(path)) if not lint.is_warning(e)]
    assert any('media_capability_unavailable' in e for e in errors)
    assert not posts(wire,'/api/v2/media') and all('Authorization' not in call[3] for call in wire['calls'])


def test_lint_instance_failure_never_uses_permissive_cache(env,wire,monkeypatch):
    cfg,adapter,repo=env;mm.cache(cfg,mm.capabilities(limits(),wire['url']))
    def unavailable(*a,**k):raise OSError('synthetic connectivity failure')
    monkeypatch.setattr(mm,'_json',unavailable)
    assert media_delivery.lint_notes(cfg,{'media':[{'file':'a.png','alt':'点'}]})==['media_capability_unavailable']
