"""Regenerate the fixed Unicode 17.0.0 tables; no network or runtime dependency.

Usage: python tools/generate_graphemes.py SOURCE_DIRECTORY OUTPUT_PY
SOURCE_DIRECTORY contains the four pinned files listed below. Official test
vectors live separately in tests/fixtures/GraphemeBreakTest-17.0.0.txt.
"""
from pathlib import Path
import hashlib
import sys

VERSION = '17.0.0'
# Hashes fixed at implementation review; see docs/Unicode_文字数.md.
SOURCES = {'GraphemeBreakProperty.txt': 'd6b51d1d2ae5c33b451b7ed994b48f1f4dc62b2272a5831e7fd418514a6bae89', 'DerivedCoreProperties.txt': '24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08', 'emoji-data.txt': '2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b', 'LICENSE.txt': 'e7a93b009565cfce55919a381437ac4db883e9da2126fa28b91d12732bc53d96'}


def read(root,name):
    data=(root/name).read_bytes()
    if hashlib.sha256(data).hexdigest()!=SOURCES[name]:
        raise ValueError('Unicode input hash mismatch: '+name)
    return data.decode('utf-8')


def ranges(text, selector):
    out=[]
    for line in text.splitlines():
        line=line.split('#',1)[0].strip()
        if not line:continue
        fields=[v.strip() for v in line.split(';')]
        value=selector(fields)
        if value is None:continue
        span=fields[0].split('..');a=int(span[0],16);b=int(span[-1],16)
        out.append((a,b,value))
    out.sort()
    merged=[]
    for a,b,value in out:
        if merged and a<=merged[-1][1]:raise ValueError('overlapping property ranges')
        if merged and a==merged[-1][1]+1 and value==merged[-1][2]:
            merged[-1]=(merged[-1][0],b,value)
        else:merged.append((a,b,value))
    return merged


def generate(root):
    license_text=read(root,'LICENSE.txt')
    out=['# Generated by tools/generate_graphemes.py; do not hand edit.']
    out.extend('# '+line for line in license_text.splitlines())
    out.extend(['',f'UNICODE_VERSION = {VERSION!r}','SOURCE_SHA256 = '+repr(SOURCES),''])
    inputs=[('GCB', 'GraphemeBreakProperty.txt',lambda f:f[1]),
            ('INCB','DerivedCoreProperties.txt',lambda f:f[2] if len(f)>2 and f[1]=='InCB' else None),
            ('EP','emoji-data.txt',lambda f:'Extended_Pictographic' if f[1]=='Extended_Pictographic' else None)]
    for name,filename,select in inputs:
        out.append(name+' = (')
        out.extend('    '+repr(row)+',' for row in ranges(read(root,filename),select))
        out.extend([')',''])
    return '\n'.join(out).encode('utf-8')


if __name__=='__main__':
    Path(sys.argv[2]).write_bytes(generate(Path(sys.argv[1])))
